name: dotnet-crank

on:
  push:
    tags:
      - "dotnet-crank.*"  

jobs:
  build:
      name: Build and upload crank artifact
      runs-on: ubuntu-latest    
      strategy:
        matrix:
          targets: [ "linux-x64", "win-x64"]

      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
      - name:  Publish
        env:
              RID: ${{ matrix.targets }}
        run: |
          git clone https://github.com/dotnet/crank.git
          cd crank 
          git checkout main

          dotnet publish src/Microsoft.Crank.Controller/Microsoft.Crank.Controller.csproj -c Release --framework net7.0 -r $RID -p:PublishSingleFile=true -p:PublishTrimmed=true -p:DebugType=None -p:DebugSymbols=false -p:EnableCompressionInSingleFile=true --self-contained true --output /home/runner/work/clis/$RID

      - name: Package assets
        env:
            RID: ${{ matrix.targets }}
        run: |
            ver=$(date "+%Y%m%d%H%M%S")
            mkdir /home/runner/work/release
            ls /home/runner/work/clis/
            zip -j /home/runner/work/release/dotnet-crank.$ver.$RID.zip /home/runner/work/clis/$RID/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
            name: dotnet-crank
            path: /home/runner/work/release

  release:
        name: Publish release
        needs: ['build']
        runs-on: ubuntu-latest
    
        steps:          
          - name: Download build artifacts
            uses: actions/download-artifact@v3
            with:
              name: dotnet-crank
              path: dotnet-crank
          - name: list dotnet-crank
            run: ls dotnet-crank    
          - name: Release
            uses: softprops/action-gh-release@v1
            with:
                files: dotnet-crank/**