name: cw-crank-agent

on:
  push:
    branches:
      - cw-crank-agent

env:
  IMAGE_NAME: crankagent_cw

jobs:
  build:
    runs-on: ubuntu-latest          
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name:  Publish
        run: |
          git clone https://github.com/catcherwong/crank.git
          cd  crank
          git checkout all

          ver=$(date "+%Y%m%d%H%M%S")
          docker build -t ghcr.io/catcherwong/crankagent_cw:$ver -f docker/agent/Dockerfile .

          docker push ghcr.io/catcherwong/crankagent_cw:$ver
