name: dotnet-crank-agent

on:
  push:
    branches:
      - dotnet-crank-agent

jobs:
  build:
    runs-on: ubuntu-latest          
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name:  Publish
        run: |
          git clone https://github.com/dotnet/crank.git
          cd  crank
          git checkout main
          
          
          ver=$(date "+%Y%m%d%H%M%S")
          docker build -t ghcr.io/catcherwong/crankagent_dotnet:$ver -f docker/agent/Dockerfile .

          docker push ghcr.io/catcherwong/crankagent_dotnet:$ver
